# Generated by Django 3.2.4 on 2021-06-25 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.CharField(default='未知', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4e0addcb-d71c-4bb5-9c74-f34b805695a7'), primary_key=True, serialize=False),
        ),
    ]
