# Generated by Django 3.2.4 on 2021-06-25 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6dd4c02b-ab84-4024-8007-44c20ec30998'), primary_key=True, serialize=False),
        ),
    ]
