# Generated by Django 3.2.2 on 2022-05-14 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitors', '浏览者'), ('lucky_draw', '抽奖者'), ('judges', '评委'), ('senior_judges', '高级评委'), ('poster_manager', '海报管理者'), ('admin', '管理员')], default='visitors', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4b200f8-592b-48ad-b688-76f7a8c7cef6'), primary_key=True, serialize=False),
        ),
    ]
