# Generated by Django 3.2.2 on 2022-05-14 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220514_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('136ef294-efef-473b-8abb-87c67bc38363'), primary_key=True, serialize=False)),
                ('title', models.CharField(default='无', max_length=128)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a210aa72-4056-471a-9425-5587590a5d20'), primary_key=True, serialize=False),
        ),
    ]
