# Generated by Django 3.2.2 on 2022-05-15 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220514_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addr',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffec5c7a-8285-463b-a153-56cdc31a1173'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28b607c9-028f-4336-aeb6-39d9e98a0bd1'), primary_key=True, serialize=False),
        ),
    ]
