# Generated by Django 3.2.2 on 2022-05-15 01:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220515_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f6ebf185-edb4-4286-b46b-6dfcc23df0c5'), primary_key=True, serialize=False)),
                ('title', models.CharField(default='无', max_length=128)),
                ('summary', models.CharField(default='无', max_length=256)),
                ('image_path', models.CharField(default='/', max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd3170f9-2241-4ea3-910f-4fa1539aa6e3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3086bcef-f148-4a33-97a9-cc11120a8698'), primary_key=True, serialize=False),
        ),
    ]
