# Generated by Django 3.2.2 on 2022-05-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220515_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='vote_number',
            field=models.IntegerField(default=0),
        ),
    ]
