# Generated by Django 3.2.2 on 2022-05-15 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_luck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('visitors', '浏览者'), ('lucky_draw', '抽奖者'), ('judges', '评委'), ('senior_judges', '高级评委'), ('poster_manager', '海报管理者'), ('admin', '管理员')], default='visitors', max_length=64)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='luck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
