# Generated by Django 3.2.2 on 2022-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220515_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
