# Generated by Django 3.2.2 on 2022-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_poster_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
