# Generated by Django 3.2.2 on 2022-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_poster_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='score',
            new_name='one_score',
        ),
        migrations.AddField(
            model_name='poster',
            name='two_score',
            field=models.IntegerField(default=0),
        ),
    ]
