# Generated by Django 3.2.2 on 2022-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220519_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='one_score',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='two_score',
        ),
        migrations.AddField(
            model_name='poster',
            name='grade',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='poster',
            name='one_score_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='poster',
            name='two_score_number',
            field=models.IntegerField(default=1),
        ),
    ]
