# Generated by Django 3.2.2 on 2022-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220519_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='one_score_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poster',
            name='two_score_total',
            field=models.IntegerField(default=0),
        ),
    ]
