# Generated by Django 3.2.2 on 2022-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220519_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='poster_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poster',
            name='one_score_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poster',
            name='two_score_number',
            field=models.IntegerField(default=0),
        ),
    ]
