# Generated by Django 3.2.2 on 2022-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220519_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='one_score_avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poster',
            name='two_score_avg',
            field=models.IntegerField(default=0),
        ),
    ]
